# Generated by Django 4.2.6 on 2023-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(max_length=100)),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Copa_Libertadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeon', models.CharField(max_length=150)),
                ('subcampeon', models.CharField(max_length=150)),
                ('año', models.DateField(null=True)),
                ('sede', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=200)),
                ('articulo', models.CharField(max_length=1500)),
                ('autor', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
