# Generated by Django 4.2.6 on 2023-11-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Noticias',
        ),
    ]
