# Generated by Django 4.2.6 on 2023-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_noticia_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copa_libertadores',
            name='año',
            field=models.DateField(blank=True),
        ),
    ]
