# Generated by Django 4.2.6 on 2023-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_copa_libertadores_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copa_libertadores',
            name='año',
            field=models.IntegerField(),
        ),
    ]
