# Generated by Django 4.2.6 on 2023-11-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_copa_libertadores_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificatorias',
            old_name='partidos_empatados',
            new_name='empatados',
        ),
        migrations.RenameField(
            model_name='clasificatorias',
            old_name='partidos_ganados',
            new_name='ganados',
        ),
        migrations.RenameField(
            model_name='clasificatorias',
            old_name='partidos_perdidos',
            new_name='perdidos',
        ),
    ]
