# Generated by Django 4.2.6 on 2023-11-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_rename_partidos_empatados_clasificatorias_empatados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copa_libertadores',
            old_name='sede',
            new_name='estadio',
        ),
    ]
